// Generated by gencpp from file h4r_ev3_msgs/Seek.msg
// DO NOT EDIT!


#ifndef H4R_EV3_MSGS_MESSAGE_SEEK_H
#define H4R_EV3_MSGS_MESSAGE_SEEK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h4r_ev3_msgs
{
template <class ContainerAllocator>
struct Seek_
{
  typedef Seek_<ContainerAllocator> Type;

  Seek_()
    : heading(0.0)
    , distance(0.0)  {
    }
  Seek_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::h4r_ev3_msgs::Seek_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h4r_ev3_msgs::Seek_<ContainerAllocator> const> ConstPtr;

}; // struct Seek_

typedef ::h4r_ev3_msgs::Seek_<std::allocator<void> > Seek;

typedef boost::shared_ptr< ::h4r_ev3_msgs::Seek > SeekPtr;
typedef boost::shared_ptr< ::h4r_ev3_msgs::Seek const> SeekConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h4r_ev3_msgs::Seek_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace h4r_ev3_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'h4r_ev3_msgs': ['/home/cwiz/catkin_ws/src/h4r_ev3_ctrl/h4r_ev3_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h4r_ev3_msgs::Seek_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h4r_ev3_msgs::Seek_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h4r_ev3_msgs::Seek_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3897b918b84041e153db3b3eea1a1e19";
  }

  static const char* value(const ::h4r_ev3_msgs::Seek_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3897b918b84041e1ULL;
  static const uint64_t static_value2 = 0x53db3b3eea1a1e19ULL;
};

template<class ContainerAllocator>
struct DataType< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h4r_ev3_msgs/Seek";
  }

  static const char* value(const ::h4r_ev3_msgs::Seek_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 heading\n"
"float64 distance\n"
;
  }

  static const char* value(const ::h4r_ev3_msgs::Seek_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Seek_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h4r_ev3_msgs::Seek_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h4r_ev3_msgs::Seek_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H4R_EV3_MSGS_MESSAGE_SEEK_H
